### PR TITLE
Bump Go to 1.16

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
I cannot reproduce the build error locally

**Comment by kanchwala-yusuf** [comment]
Hi @gliptak,
Can you trying running `go mod tidy` and try to push the go mod changes?

**Comment by gliptak** [comment]
@kanchwala-yusuf thank you for the pointer. After running `go mod tidy` the build still shows the same error

**Comment by gliptak** [comment]
https://github.com/golang/go/issues/44129

**Comment by patilpankaj212** [comment]
closing this PR, go version updated in #836

**Comment by kanchwala-yusuf** [comment]
Hi @gliptak , 
Thank you for raising a PR! but, there was a need for us to bump up the go version immediately hence #836

**Pull request closed without merging**
