### PR TITLE
Refactor: Fix check for empty string

### PR DESCRIPTION
**Pull request by withshubh**
#### Description
Hi :wave: I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some interesting [code quality issues](https://deepsource.io/gh/withshubh/terrascan/issues/). This PR fixes a few of them.

#### Summary of changes
- added .deepsource.toml file
- Fix check for empty string

### CODE REVIEW

**Comment by kanchwala-yusuf** [comment]
Hey @withshubh , 

Can you please share the steps to execute `DeepSource`? How can we add this to our existing CI pipeline?

**Comment by withshubh** [comment]
> Hey @withshubh ,
> 
> Can you please share the steps to execute `DeepSource`? How can we add this to our existing CI pipeline?

#### Integrating DeepSource to continuously analyze your repository:
- Install DeepSource on your repository after signing up from [here](https://deepsource.io/signup).
- Create `.deepsource.toml` configuration specific to this repo or merge this PR to use the configuration I have used to run the analysis on the fork of this repo.
- Activate analysis [here](https://deepsource.io/gh/accurics/terrascan/).

I work at DeepSource, let me know if you have any question/suggestion regarding our go analyzer.

**Comment by withshubh** [comment]
@kanchwala-yusuf :wave: Did you activate the analysis? 

let me know if you need any assistance! :sparkling_heart:

**Comment by jlk** [comment]
Hey @withshubh! Big fan of DS, thanks for reaching out.

We've had a few chats on this PR. The particular issue which DS is flagging is purely a stylistic issue, so we won't be changing the code. We've really nerded out on it, down to looking at compiler output across several different CPU architectures, and it seems the golang compiler is optimizing both styles of writing the comparison down to the same machine instructions.

We don't have the bandwidth to take on another tool at the moment, but if you see other issues that you feel we should address, don't hesitate to create another PR.

**Comment by withshubh** [comment]
@jlk Thank You for your response :sparkling_heart: 

> We don't have the bandwidth to take on another tool at the moment, but if you see other issues that you feel we should address, don't hesitate to create another PR.

Sure thing.

**Pull request closed without merging**
